#FROM openjdk:8-jdk
#
#WORKDIR /apps/
#
#COPY build/libs/*.jar app.jar
#
#ENTRYPOINT ["java","-jar","/apps/app.jar"]
#
## 1. gradle执行构建, 构建出最新项目.
## 2. docker构建镜像: docker build  -t springio/gs-spring-boot-docker .
